package com.payroll.web.security;

import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * Deterministic (unsalted) hash for machine API keys. Argon2 is intentionally
 * not used here — unlike a human password, a sync API key is high-entropy and
 * generated by us, and the lookup path needs to find the matching {@code SyncClient}
 * by hash equality, which an Argon2/BCrypt random salt would make impossible.
 * SHA-256 is sufficient to ensure the raw key is never recoverable from storage.
 */
@Component
public class ApiKeyHasher {

    public String hash(String rawApiKey) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] bytes = digest.digest(rawApiKey.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(bytes);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 not available", e);
        }
    }
}
